services:
  employee-gateway:
    image: ${DOCKERHUB_USERNAME}/toolmarket-employee-gateway:latest
    networks:
      - gateway
      - internal
    env_file: .env
    depends_on: [api]

  user-gateway:
    image: ${DOCKERHUB_USERNAME}/toolmarket-user-gateway:latest
    networks:
      - gateway
      - internal
    env_file: .env
    depends_on: [api]

  nginx:
    image: nginx:1.29.6-alpine
    networks:
      - public
      - gateway 
    env_file: .env
    ports: ["8080:80", "443:443"]
    volumes:
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/templates:/etc/nginx/templates
      - assets_data:/assets:ro
    depends_on: [employee-gateway, user-gateway, grafana, prometheus]

  db:
    image: ${DOCKERHUB_USERNAME}/toolmarket-db:latest
    networks:
      - internal
    env_file: .env
    command: >
      -c shared_preload_libraries=pg_cron,http
      -c cron.database_name=${POSTGRES_DB}
    # ports: ["5432:5432"]
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./db/db_inits/pre-seed:/docker-entrypoint-initdb.d
    restart: unless-stopped

  api:
    image: ${DOCKERHUB_USERNAME}/toolmarket-api:latest
    networks:
      - internal
      - gateway
    # ports: ["5001:8000"]
    depends_on: [db]
    env_file: .env
    volumes:
      - assets_data:/app/assets
    restart: on-failure

  prometheus:
    image: prom/prometheus:v3
    env_file: .env
    networks:
      - gateway
      - internal
    # ports: ["9090:9090"]
    command:
       - '--config.file=/etc/prometheus/prometheus.yml'
       - --storage.tsdb.path=/prometheus
       - --web.console.templates=/etc/prometheus/consoles
       - --web.console.libraries=/etc/prometheus/console_libraries
       - '--web.external-url=${PR_SERVER_ROOT}'
       - '--web.route-prefix=/'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on: [employee-gateway, user-gateway, api, db]

  grafana:
    image: grafana/grafana:12.3
    networks:
      - gateway
      - internal
    # ports: ["3000:3000"]
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    env_file: .env
    depends_on: [prometheus]

volumes:
  postgres_data:
  assets_data:

networks:
  public:
  gateway:
  internal:
