{
 "title": "API Stats",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "HTTP Requests Created",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "http_requests_created", "legendFormat": "HTTP Requests Created" }
   ]
  },
  {
   "title": "Request Duration ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(toolmarket_http_request_duration_seconds_sum[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Is UP?",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP Requests Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "toolmarket_http_requests_total", "legendFormat": "{{label_name}}" }
   ]
  }
 ]
}