{
 "title": "Market stats",
 "time": { "from": "now/d", "to": "now/d" },
 "panels": [
  {
   "title": "Products Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "toolmarket_products_total", "legendFormat": "Products Total" }
   ]
  },
  {
   "title": "Orders",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "toolmarket_orders_total", "legendFormat": "Total Orders" },
    {
     "expr": "toolmarket_orders_by_status_total{status=\"completed\"}",
     "legendFormat": "Orders Completed"
    },
    {
     "expr": "toolmarket_orders_by_status_total{status=\"payed\"}",
     "legendFormat": "Orders Payed"
    },
    {
     "expr": "toolmarket_orders_by_status_total{status=\"cancelled\"}",
     "legendFormat": "Orders Cancelled"
    }
   ]
  },
  {
   "title": "User Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "toolmarket_users_total", "legendFormat": "User count" }
   ]
  },
  {
   "title": "Units in stock",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "toolmarket_stock_units_total", "legendFormat": "Total Units In Stock" },
    {}
   ]
  },
  {
   "title": "Revenue (total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "toolmarket_revenue_base_total", "legendFormat": "Total Revenue" },
    {}
   ]
  },
  {
   "title": "Payments",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "toolmarket_payments_total", "legendFormat": "Total Payments" },
    {
     "expr": "toolmarket_payments_completed_total",
     "legendFormat": "Payments Complete"
    }
   ]
  }
 ]
}